hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "868ddcb532c17eeffd2607e0da02a2fc2d54f09acf31b06f7e286f2a1749f43a"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "7506ce51c764f8b278b1b45f27cdaec9946da202520ca713709cbdb69a9568a0"

[[files]]
file = "config/fml.toml"
hash = "46725924745ae5627b0c51ebd495083b10d21ab4c0c7629833c375551329e4da"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "00641ee11fabb2c51b3c795a90dfe8a6dc492380c7cacd94a2024dd1b6eecdc7"

[[files]]
file = "config/modernfix-common.toml"
hash = "72ca2bcea2a9946a3a54842f14eff6f7b47d8fc96ef497c1b56406643b153fd7"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "81c8b4401bded106d5c592fb3d325e09dcd67049b633bf7049675f23d46afda3"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "69b07ae8cb0d37e1179a76c6c182f6746e7f86978e519e74162b8e30b6791452"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "7823fc7bb5b474d3a39a2ff8e71054812499439cef63fbaa7124930de296c7cf"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "bc7cfadfe7121fdbd356c7992705ea6f484de518d3fd473eb8c59ea93e79a04d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "4aab6ffc7d48092933083ce1a883ec72827dd6da1ccaae6852154b3e4eaead5d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "ef55a85f0905e41d93de2b7e53266d393bf58f43917d9b15ea8f66b757a5996d"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "c951505f545e9d7f57ba66201609eac1792469e22fa13efcade818fc8b61cbe2"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/ok_zoomer/config.toml"
hash = "a7c05cd6ad8a8fcd1399b40aefe221c9cbaa67e58fac4b477bda534ec92d9ded"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "481193336b67c5a9a82beec77880556f3b92fd792cd8ea4414a904dd66acd733"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "5b24c9a57bb6092df95d9e8ec3c79574103967cef4db94508b9b172df1e447e5"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "244a5a217b4604782a66736cae23717c7871acd0e2bbd51dc2b28e4b642885f2"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "873f9f7e42d053b79f51f14e804ff09e12ff2bc9f78d9bcb96ecc25a1332c5c9"

[[files]]
file = "config/yosbr/options.txt"
hash = "5f7a76da45c11e03698f375bd3612d57a729a09f604f21d8bc647d069eaf0c7f"

[[files]]
file = "mods/animatica.pw.toml"
hash = "ff31791271197f8122fb52893e7e67d86ba038dd0e77e57227ef84de8f7e069e"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "a850075a3b7e380701f0291f6151487d0a05bb54db125c8edf9f96a696b73188"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "eeec057d3fb7f0c076d271a1c3608b67d88895e59a18bb9b5a5fe604b65fc6e6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "52e2cb54ee2933bf00e9b7886f47938a2dce1bf998293be2b38552083ffa5f9a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "e487d315e7a44f917cd1ddc2da1b26e65968bc19fe6c0ac868dab3d2bb97bbf1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "4041e8467de084fbd33e4c99cd81c3edb064332ab2992a94eab7c6acbff619f5"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ae6fd52d8bdcbeca5bbe6db840f22f92c1928fe0fda22017b19612b9b00a245a"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b42ea604c46fc73d9474ebc9d6d3d64a1efe6b9d5df8512c71a86f820eb8a105"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "68e0010a541dfab4ada1786114b5ac4cbd5b083519663757fcdad0a0fe186aab"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4cd35c49af924af84f832aca56a5efc6130a24780cd25c631b12407860a796ab"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "11e43d47773d438897c9e445a1231ab2158b99ba24c7e59a6d69e62c1349b4b2"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "18e6869e7b42841227824563fc774e2e268040d88167b0ab47187298f29b0bb6"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7004d6d04c19eaa92fda0b47ac70b7c85987c47cc1431313014c5e9367679173"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "73360e397134d238ee8fd21d33fd7f9275e9441f74f8f1b6ed92278877c0b9f1"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "a830f9e0393be04dd0a8a3a845b27e90cd34961887403c800e296182283d9c3e"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "f9c118b7a66238a7f9e052705e82402e57c7a5b753d62d679b94701ede479752"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3d47b1d933d04934a606be1cbb67481860c3d68c9ed4efc387c7745d23b732a7"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "27302b0087cf53570cd7a3b4eb550a208cbb6f6ba07210c604176155f39e0078"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "07f04b4589c6ffe170332cae7d62badefa9ea7753d9621dbdb968c937a928f6e"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "e226757905a685aa4b5a61f3d060d55a01bbd043aabd18d3e8287dd2d8ebfb7b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e7544296d2cdd85e43a60cf3e7a8f3e036782e14abc4efeea7f064d980d59dd5"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "43b7544c0a49c9368caf33a1529a720c6fadb17f7d07db6a8e952b514b5a862c"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6f0dcbcffd4400c6cef07f1eeb48cdc25bac0fa01270936feab4c549aff4738e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6ae9430e2319ead3cb8580633c13d119c9d06f097204f3f8afbc0e4681e9a807"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "533cc65290311d51c42bfa7a5a700254db6401ae5a90829fb7863b17db9665d1"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "0846c709603ff778d27f6afe12caa9fedf0648b7d7182a969fd08fe6432b5cc9"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "1121ffc2012bbbf0b619a16b953d5951c41a9ef545285d01f31995b3ba6b2b8c"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "7333c29c224d843384e26b2c7d9af1d31dada870d776fb1ad8f3d8c3040b313d"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "880e51166c531f473f9bdef251a6c42c6d13f4283bcc8e27d66999aef57c9a59"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "748d7eb08f3d2c362aebf9ee417706b181257b7d5f4a2003ec93340d5b7b881d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "6b5e9ad0332e9270c3c5064efeffd64dfa0835e46af476892713f62b4afef018"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "cc5914bc09a7362dfd660fbeff105d3595b19de9c6491327272f85c557d4aa3b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "a73dfb1bf6884ae786b2def0624dee9010bf121d0b5678b46043d9312f54b501"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "53e01bde67391ead9e5bcf1e86479aebd9ddb0345f871ce4b49afd655b238523"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "b844c10676b5911a4d2af32710d21fa22eafafcb6e1e3505fb8651b643cd99f7"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "5fa26648cc2ffa6af3afe4a8df882bbf3fad12b232de971652f8633404d7f21d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "e07f7885481b48bd70fe24d3e309cc1c6e53191bdfa5d9d0c1bf050d854443a0"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "e8a4a5ded3fd3ad71f8882d870541a3edf5d8286d9182e9fd8c5990e570e7463"
metafile = true
