name = "Drill"
author = "SkywardMC"
version = "1.0.0+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f540969affd48422dfba9d8bf8c3d18c7dad221bbae237c9746be8f1506888a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
