name = "Drill"
author = "SkywardMC"
version = "1.0.0+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88c23439d5e5b57d66d3c16b5a812e280de69bfed5c7f0ef9458accede8b8ab7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
