name = "Drill"
author = "SkywardMC"
version = "1.0.0+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78371f36f50c9def298d2a2c58e87479fbb6b0601223158f5f292651c580c96a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
