name = "Drill"
author = "SkywardMC"
version = "xxxxxx.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4eacb7a237f58943ab8f79dd6c05675aa073c621c39a311f2b786cf6dcd7557"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.129"
