name = "Drill"
author = "SkywardMC"
version = "0.7.0-1.34.0+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7f5a59ce5fd63cd62d3cac0b000fcc31bab4b11081158270a112cefb965e52b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
